import streamlit as st
st.title("My first App")
st.write("Happy new year")
st.header("Fillup Your Form Details Carefully")
st.text("Enter Your Details")
st.text_input("Enter Your Name")
st.number_input("Enter Your Age")
st.selectbox("Choose Your city",["Bihar","Hyderabad","Dehradun","Bangalore"])
st.radio("Choose Your Gender",["Male","Female","Others"])
st.text("Choose your Subjects")
st.checkbox("Maths")
st.checkbox("Physics")
st.checkbox("Chemistry")
st.checkbox("Biology")
st.button("Click")
st.success("Details submitted successfully..")